# Generated by Django 4.2.9 on 2024-01-29 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comment_bid_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
