# Generated by Django 4.2.9 on 2024-02-01 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='listing_bidders', to=settings.AUTH_USER_MODEL),
        ),
    ]
