# Generated by Django 4.2.9 on 2024-02-01 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auctionlisting_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bids',
            field=models.ManyToManyField(blank=True, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
