# Generated by Django 4.2.9 on 2024-02-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlisting_comments_alter_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='watched_by',
        ),
        migrations.AddField(
            model_name='comment',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
