# Generated by Django 4.2.9 on 2024-02-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_auctionlisting_watched_by_comment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
    ]
